/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.0.2
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalSDK.Server.Client.OpenAPIDateConverter;
using System.Reflection;

namespace OneSignalSDK.Server.Model
{
    /// <summary>
    /// DateTimeOrLong
    /// </summary>
    [JsonConverter(typeof(DateTimeOrLongJsonConverter))]
    [DataContract(Name = "DateTimeOrLong")]
    public partial class DateTimeOrLong : AbstractOpenAPISchema, IEquatable<DateTimeOrLong>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DateTimeOrLong" /> class
        /// with the <see cref="DateTime" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of DateTime.</param>
        public DateTimeOrLong(DateTime actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DateTimeOrLong" /> class
        /// with the <see cref="long" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of long.</param>
        public DateTimeOrLong(long actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(DateTime))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(long))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: DateTime, long");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `DateTime`. If the actual instance is not `DateTime`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of DateTime</returns>
        public DateTime GetDateTime()
        {
            return (DateTime)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `long`. If the actual instance is not `long`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of long</returns>
        public long GetLong()
        {
            return (long)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DateTimeOrLong {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, DateTimeOrLong.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of DateTimeOrLong
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of DateTimeOrLong</returns>
        public static DateTimeOrLong FromJson(string jsonString)
        {
            DateTimeOrLong newDateTimeOrLong = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newDateTimeOrLong;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(DateTime).GetProperty("AdditionalProperties") == null)
                {
                    newDateTimeOrLong = new DateTimeOrLong(JsonConvert.DeserializeObject<DateTime>(jsonString, DateTimeOrLong.SerializerSettings));
                }
                else
                {
                    newDateTimeOrLong = new DateTimeOrLong(JsonConvert.DeserializeObject<DateTime>(jsonString, DateTimeOrLong.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("DateTime");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into DateTime: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(long).GetProperty("AdditionalProperties") == null)
                {
                    newDateTimeOrLong = new DateTimeOrLong(JsonConvert.DeserializeObject<long>(jsonString, DateTimeOrLong.SerializerSettings));
                }
                else
                {
                    newDateTimeOrLong = new DateTimeOrLong(JsonConvert.DeserializeObject<long>(jsonString, DateTimeOrLong.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("long");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into long: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newDateTimeOrLong;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DateTimeOrLong);
        }

        /// <summary>
        /// Returns true if DateTimeOrLong instances are equal
        /// </summary>
        /// <param name="input">Instance of DateTimeOrLong to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DateTimeOrLong input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for DateTimeOrLong
    /// </summary>
    public class DateTimeOrLongJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(DateTimeOrLong).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType == JsonToken.StartArray)
            {
                return DateTimeOrLong.FromJson(JArray.Load(reader).ToString(Formatting.None));
            }
            else if(reader.TokenType == JsonToken.StartObject)
            {
                return DateTimeOrLong.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            else if(reader.TokenType != JsonToken.Null)
            {
                return DateTimeOrLong.FromJson(reader.Value.ToString());
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
