/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// CopyTemplateRequest
    /// </summary>
    [DataContract(Name = "CopyTemplateRequest")]
    public partial class CopyTemplateRequest : IEquatable<CopyTemplateRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CopyTemplateRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CopyTemplateRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CopyTemplateRequest" /> class.
        /// </summary>
        /// <param name="targetAppId">Destination OneSignal App ID in UUID v4 format. (required).</param>
        public CopyTemplateRequest(string targetAppId = default(string))
        {
            // to ensure "targetAppId" is required (not null)
            if (targetAppId == null)
            {
                throw new ArgumentNullException("targetAppId is a required property for CopyTemplateRequest and cannot be null");
            }
            this.TargetAppId = targetAppId;
        }

        /// <summary>
        /// Destination OneSignal App ID in UUID v4 format.
        /// </summary>
        /// <value>Destination OneSignal App ID in UUID v4 format.</value>
        [DataMember(Name = "target_app_id", IsRequired = true, EmitDefaultValue = false)]
        public string TargetAppId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CopyTemplateRequest {\n");
            sb.Append("  TargetAppId: ").Append(TargetAppId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CopyTemplateRequest);
        }

        /// <summary>
        /// Returns true if CopyTemplateRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CopyTemplateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CopyTemplateRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TargetAppId == input.TargetAppId ||
                    (this.TargetAppId != null &&
                    this.TargetAppId.Equals(input.TargetAppId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TargetAppId != null)
                {
                    hashCode = (hashCode * 59) + this.TargetAppId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
