/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// Writable fields for Create journey. Journeys are always created in the draft state. Server-controlled fields such as state or id are rejected.
    /// </summary>
    [DataContract(Name = "CreateJourneyRequest")]
    public partial class CreateJourneyRequest : IEquatable<CreateJourneyRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateJourneyRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateJourneyRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateJourneyRequest" /> class.
        /// </summary>
        /// <param name="name">Journey name, up to 300 characters. (required).</param>
        /// <param name="description">Optional journey description, up to 1024 characters..</param>
        /// <param name="audience">audience.</param>
        /// <param name="earlyExit">earlyExit.</param>
        /// <param name="reentryRules">reentryRules.</param>
        /// <param name="schedule">schedule.</param>
        /// <param name="nodes">Ordered list of journey nodes. Server-assigned id fields are rejected on create..</param>
        public CreateJourneyRequest(string name = default(string), string description = default(string), JourneyAudience audience = default(JourneyAudience), JourneyEarlyExit earlyExit = default(JourneyEarlyExit), JourneyReentryRules reentryRules = default(JourneyReentryRules), JourneySchedule schedule = default(JourneySchedule), List<JourneyNode> nodes = default(List<JourneyNode>))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateJourneyRequest and cannot be null");
            }
            this.Name = name;
            this.Description = description;
            this.Audience = audience;
            this.EarlyExit = earlyExit;
            this.ReentryRules = reentryRules;
            this.Schedule = schedule;
            this.Nodes = nodes;
        }

        /// <summary>
        /// Journey name, up to 300 characters.
        /// </summary>
        /// <value>Journey name, up to 300 characters.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Optional journey description, up to 1024 characters.
        /// </summary>
        /// <value>Optional journey description, up to 1024 characters.</value>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Audience
        /// </summary>
        [DataMember(Name = "audience", EmitDefaultValue = false)]
        public JourneyAudience Audience { get; set; }

        /// <summary>
        /// Gets or Sets EarlyExit
        /// </summary>
        [DataMember(Name = "early_exit", EmitDefaultValue = true)]
        public JourneyEarlyExit EarlyExit { get; set; }

        /// <summary>
        /// Gets or Sets ReentryRules
        /// </summary>
        [DataMember(Name = "reentry_rules", EmitDefaultValue = true)]
        public JourneyReentryRules ReentryRules { get; set; }

        /// <summary>
        /// Gets or Sets Schedule
        /// </summary>
        [DataMember(Name = "schedule", EmitDefaultValue = true)]
        public JourneySchedule Schedule { get; set; }

        /// <summary>
        /// Ordered list of journey nodes. Server-assigned id fields are rejected on create.
        /// </summary>
        /// <value>Ordered list of journey nodes. Server-assigned id fields are rejected on create.</value>
        [DataMember(Name = "nodes", EmitDefaultValue = false)]
        public List<JourneyNode> Nodes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateJourneyRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Audience: ").Append(Audience).Append("\n");
            sb.Append("  EarlyExit: ").Append(EarlyExit).Append("\n");
            sb.Append("  ReentryRules: ").Append(ReentryRules).Append("\n");
            sb.Append("  Schedule: ").Append(Schedule).Append("\n");
            sb.Append("  Nodes: ").Append(Nodes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateJourneyRequest);
        }

        /// <summary>
        /// Returns true if CreateJourneyRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateJourneyRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateJourneyRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Audience == input.Audience ||
                    (this.Audience != null &&
                    this.Audience.Equals(input.Audience))
                ) && 
                (
                    this.EarlyExit == input.EarlyExit ||
                    (this.EarlyExit != null &&
                    this.EarlyExit.Equals(input.EarlyExit))
                ) && 
                (
                    this.ReentryRules == input.ReentryRules ||
                    (this.ReentryRules != null &&
                    this.ReentryRules.Equals(input.ReentryRules))
                ) && 
                (
                    this.Schedule == input.Schedule ||
                    (this.Schedule != null &&
                    this.Schedule.Equals(input.Schedule))
                ) && 
                (
                    this.Nodes == input.Nodes ||
                    this.Nodes != null &&
                    input.Nodes != null &&
                    this.Nodes.SequenceEqual(input.Nodes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                if (this.Audience != null)
                {
                    hashCode = (hashCode * 59) + this.Audience.GetHashCode();
                }
                if (this.EarlyExit != null)
                {
                    hashCode = (hashCode * 59) + this.EarlyExit.GetHashCode();
                }
                if (this.ReentryRules != null)
                {
                    hashCode = (hashCode * 59) + this.ReentryRules.GetHashCode();
                }
                if (this.Schedule != null)
                {
                    hashCode = (hashCode * 59) + this.Schedule.GetHashCode();
                }
                if (this.Nodes != null)
                {
                    hashCode = (hashCode * 59) + this.Nodes.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
