/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// Channel: Email Present only when this notification&#39;s &#x60;kind&#x60; is \&quot;warmup\&quot;. The Auto Warm Up campaign&#39;s stage schedule, scheduling strategy, and live status.
    /// </summary>
    [DataContract(Name = "EmailWarmUp")]
    public partial class EmailWarmUp : IEquatable<EmailWarmUp>, IValidatableObject
    {
        /// <summary>
        /// How the stage schedule was produced:   * &#x60;recommended&#x60; - OneSignal generated (and may still adjust) the schedule based on past delivery volumes, scheduled Auto Warm Up emails, and the size of the current audience.   * &#x60;custom&#x60; - The stages were provided as-is in the create request. 
        /// </summary>
        /// <value>How the stage schedule was produced:   * &#x60;recommended&#x60; - OneSignal generated (and may still adjust) the schedule based on past delivery volumes, scheduled Auto Warm Up emails, and the size of the current audience.   * &#x60;custom&#x60; - The stages were provided as-is in the create request. </value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StrategyEnum
        {
            /// <summary>
            /// Enum Recommended for value: recommended
            /// </summary>
            [EnumMember(Value = "recommended")]
            Recommended = 1,

            /// <summary>
            /// Enum Custom for value: custom
            /// </summary>
            [EnumMember(Value = "custom")]
            Custom = 2

        }


        /// <summary>
        /// How the stage schedule was produced:   * &#x60;recommended&#x60; - OneSignal generated (and may still adjust) the schedule based on past delivery volumes, scheduled Auto Warm Up emails, and the size of the current audience.   * &#x60;custom&#x60; - The stages were provided as-is in the create request. 
        /// </summary>
        /// <value>How the stage schedule was produced:   * &#x60;recommended&#x60; - OneSignal generated (and may still adjust) the schedule based on past delivery volumes, scheduled Auto Warm Up emails, and the size of the current audience.   * &#x60;custom&#x60; - The stages were provided as-is in the create request. </value>
        [DataMember(Name = "strategy", EmitDefaultValue = false)]
        public StrategyEnum? Strategy { get; set; }
        /// <summary>
        /// Current status of the campaign:   * &#x60;initializing&#x60; - The stages have been submitted and the schedule is being set up.   * &#x60;draft&#x60; - The campaign has been created but has not started sending.   * &#x60;active&#x60; - The campaign is currently working through its stages.   * &#x60;finished&#x60; - All stages have completed.   * &#x60;canceled&#x60; - The campaign was canceled before finishing. 
        /// </summary>
        /// <value>Current status of the campaign:   * &#x60;initializing&#x60; - The stages have been submitted and the schedule is being set up.   * &#x60;draft&#x60; - The campaign has been created but has not started sending.   * &#x60;active&#x60; - The campaign is currently working through its stages.   * &#x60;finished&#x60; - All stages have completed.   * &#x60;canceled&#x60; - The campaign was canceled before finishing. </value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Initializing for value: initializing
            /// </summary>
            [EnumMember(Value = "initializing")]
            Initializing = 1,

            /// <summary>
            /// Enum Draft for value: draft
            /// </summary>
            [EnumMember(Value = "draft")]
            Draft = 2,

            /// <summary>
            /// Enum Active for value: active
            /// </summary>
            [EnumMember(Value = "active")]
            Active = 3,

            /// <summary>
            /// Enum Finished for value: finished
            /// </summary>
            [EnumMember(Value = "finished")]
            Finished = 4,

            /// <summary>
            /// Enum Canceled for value: canceled
            /// </summary>
            [EnumMember(Value = "canceled")]
            Canceled = 5

        }


        /// <summary>
        /// Current status of the campaign:   * &#x60;initializing&#x60; - The stages have been submitted and the schedule is being set up.   * &#x60;draft&#x60; - The campaign has been created but has not started sending.   * &#x60;active&#x60; - The campaign is currently working through its stages.   * &#x60;finished&#x60; - All stages have completed.   * &#x60;canceled&#x60; - The campaign was canceled before finishing. 
        /// </summary>
        /// <value>Current status of the campaign:   * &#x60;initializing&#x60; - The stages have been submitted and the schedule is being set up.   * &#x60;draft&#x60; - The campaign has been created but has not started sending.   * &#x60;active&#x60; - The campaign is currently working through its stages.   * &#x60;finished&#x60; - All stages have completed.   * &#x60;canceled&#x60; - The campaign was canceled before finishing. </value>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailWarmUp" /> class.
        /// </summary>
        /// <param name="stages">The campaign&#39;s sending schedule, stage by stage..</param>
        /// <param name="strategy">How the stage schedule was produced:   * &#x60;recommended&#x60; - OneSignal generated (and may still adjust) the schedule based on past delivery volumes, scheduled Auto Warm Up emails, and the size of the current audience.   * &#x60;custom&#x60; - The stages were provided as-is in the create request. .</param>
        /// <param name="status">Current status of the campaign:   * &#x60;initializing&#x60; - The stages have been submitted and the schedule is being set up.   * &#x60;draft&#x60; - The campaign has been created but has not started sending.   * &#x60;active&#x60; - The campaign is currently working through its stages.   * &#x60;finished&#x60; - All stages have completed.   * &#x60;canceled&#x60; - The campaign was canceled before finishing. .</param>
        /// <param name="isLive">Whether the campaign is currently live (actively sending)..</param>
        public EmailWarmUp(List<EmailWarmUpStage> stages = default(List<EmailWarmUpStage>), StrategyEnum? strategy = default(StrategyEnum?), StatusEnum? status = default(StatusEnum?), bool isLive = default(bool))
        {
            this.Stages = stages;
            this.Strategy = strategy;
            this.Status = status;
            this.IsLive = isLive;
        }

        /// <summary>
        /// The campaign&#39;s sending schedule, stage by stage.
        /// </summary>
        /// <value>The campaign&#39;s sending schedule, stage by stage.</value>
        [DataMember(Name = "stages", EmitDefaultValue = false)]
        public List<EmailWarmUpStage> Stages { get; set; }

        /// <summary>
        /// Whether the campaign is currently live (actively sending).
        /// </summary>
        /// <value>Whether the campaign is currently live (actively sending).</value>
        [DataMember(Name = "is_live", EmitDefaultValue = true)]
        public bool IsLive { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmailWarmUp {\n");
            sb.Append("  Stages: ").Append(Stages).Append("\n");
            sb.Append("  Strategy: ").Append(Strategy).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  IsLive: ").Append(IsLive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EmailWarmUp);
        }

        /// <summary>
        /// Returns true if EmailWarmUp instances are equal
        /// </summary>
        /// <param name="input">Instance of EmailWarmUp to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmailWarmUp input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Stages == input.Stages ||
                    this.Stages != null &&
                    input.Stages != null &&
                    this.Stages.SequenceEqual(input.Stages)
                ) && 
                (
                    this.Strategy == input.Strategy ||
                    this.Strategy.Equals(input.Strategy)
                ) && 
                (
                    this.Status == input.Status ||
                    this.Status.Equals(input.Status)
                ) && 
                (
                    this.IsLive == input.IsLive ||
                    this.IsLive.Equals(input.IsLive)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Stages != null)
                {
                    hashCode = (hashCode * 59) + this.Stages.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Strategy.GetHashCode();
                hashCode = (hashCode * 59) + this.Status.GetHashCode();
                hashCode = (hashCode * 59) + this.IsLive.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
