/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// Channel: Email One stage of an Auto Warm Up campaign&#39;s sending schedule.
    /// </summary>
    [DataContract(Name = "EmailWarmUpStage")]
    public partial class EmailWarmUpStage : IEquatable<EmailWarmUpStage>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailWarmUpStage" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EmailWarmUpStage() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EmailWarmUpStage" /> class.
        /// </summary>
        /// <param name="start">ISO 8601 timestamp for the start of this stage. Sending for this stage will not begin before this time. (required).</param>
        /// <param name="end">ISO 8601 timestamp for the end of this stage. This stage&#39;s quota is expected to be sent by this time. (required).</param>
        /// <param name="quota">Number of emails to send during this stage. (required).</param>
        public EmailWarmUpStage(DateTime start = default(DateTime), DateTime end = default(DateTime), int quota = default(int))
        {
            this.Start = start;
            this.End = end;
            this.Quota = quota;
        }

        /// <summary>
        /// ISO 8601 timestamp for the start of this stage. Sending for this stage will not begin before this time.
        /// </summary>
        /// <value>ISO 8601 timestamp for the start of this stage. Sending for this stage will not begin before this time.</value>
        [DataMember(Name = "start", IsRequired = true, EmitDefaultValue = false)]
        public DateTime Start { get; set; }

        /// <summary>
        /// ISO 8601 timestamp for the end of this stage. This stage&#39;s quota is expected to be sent by this time.
        /// </summary>
        /// <value>ISO 8601 timestamp for the end of this stage. This stage&#39;s quota is expected to be sent by this time.</value>
        [DataMember(Name = "end", IsRequired = true, EmitDefaultValue = false)]
        public DateTime End { get; set; }

        /// <summary>
        /// Number of emails to send during this stage.
        /// </summary>
        /// <value>Number of emails to send during this stage.</value>
        [DataMember(Name = "quota", IsRequired = true, EmitDefaultValue = false)]
        public int Quota { get; set; }

        /// <summary>
        /// Whether this stage has been picked up and acknowledged by the warm-up scheduler. Not accepted on create. This is only present when reading back a campaign.
        /// </summary>
        /// <value>Whether this stage has been picked up and acknowledged by the warm-up scheduler. Not accepted on create. This is only present when reading back a campaign.</value>
        [DataMember(Name = "acked", EmitDefaultValue = true)]
        public bool Acked { get; private set; }

        /// <summary>
        /// Returns false as Acked should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeAcked()
        {
            return false;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EmailWarmUpStage {\n");
            sb.Append("  Start: ").Append(Start).Append("\n");
            sb.Append("  End: ").Append(End).Append("\n");
            sb.Append("  Quota: ").Append(Quota).Append("\n");
            sb.Append("  Acked: ").Append(Acked).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EmailWarmUpStage);
        }

        /// <summary>
        /// Returns true if EmailWarmUpStage instances are equal
        /// </summary>
        /// <param name="input">Instance of EmailWarmUpStage to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EmailWarmUpStage input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Start == input.Start ||
                    (this.Start != null &&
                    this.Start.Equals(input.Start))
                ) && 
                (
                    this.End == input.End ||
                    (this.End != null &&
                    this.End.Equals(input.End))
                ) && 
                (
                    this.Quota == input.Quota ||
                    this.Quota.Equals(input.Quota)
                ) && 
                (
                    this.Acked == input.Acked ||
                    this.Acked.Equals(input.Acked)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Start != null)
                {
                    hashCode = (hashCode * 59) + this.Start.GetHashCode();
                }
                if (this.End != null)
                {
                    hashCode = (hashCode * 59) + this.End.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Quota.GetHashCode();
                hashCode = (hashCode * 59) + this.Acked.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // Quota (int) minimum
            if (this.Quota < (int)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Quota, must be a value greater than or equal to 0.", new [] { "Quota" });
            }

            yield break;
        }
    }

}
