/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// Filter
    /// </summary>
    [DataContract(Name = "Filter")]
    public partial class Filter : IEquatable<Filter>, IValidatableObject
    {
        /// <summary>
        /// Required. Operator of a filter expression.
        /// </summary>
        /// <value>Required. Operator of a filter expression.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RelationEnum
        {
            /// <summary>
            /// Enum GreaterThan for value: &gt;
            /// </summary>
            [EnumMember(Value = ">")]
            GreaterThan = 1,

            /// <summary>
            /// Enum LessThan for value: &lt;
            /// </summary>
            [EnumMember(Value = "<")]
            LessThan = 2,

            /// <summary>
            /// Enum Equal for value: &#x3D;
            /// </summary>
            [EnumMember(Value = "=")]
            Equal = 3,

            /// <summary>
            /// Enum NotEqual for value: !&#x3D;
            /// </summary>
            [EnumMember(Value = "!=")]
            NotEqual = 4,

            /// <summary>
            /// Enum Exists for value: exists
            /// </summary>
            [EnumMember(Value = "exists")]
            Exists = 5,

            /// <summary>
            /// Enum NotExists for value: not_exists
            /// </summary>
            [EnumMember(Value = "not_exists")]
            NotExists = 6,

            /// <summary>
            /// Enum TimeElapsedGt for value: time_elapsed_gt
            /// </summary>
            [EnumMember(Value = "time_elapsed_gt")]
            TimeElapsedGt = 7,

            /// <summary>
            /// Enum TimeElapsedLt for value: time_elapsed_lt
            /// </summary>
            [EnumMember(Value = "time_elapsed_lt")]
            TimeElapsedLt = 8

        }


        /// <summary>
        /// Required. Operator of a filter expression.
        /// </summary>
        /// <value>Required. Operator of a filter expression.</value>
        [DataMember(Name = "relation", EmitDefaultValue = false)]
        public RelationEnum? Relation { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Filter" /> class.
        /// </summary>
        /// <param name="field">Required. Name of the field to use as the first operand in the filter expression..</param>
        /// <param name="key">If &#x60;field&#x60; is &#x60;tag&#x60;, this field is *required* to specify &#x60;key&#x60; inside the tags..</param>
        /// <param name="value">Constant value to use as the second operand in the filter expression. This value is *required* when the relation operator is a binary operator..</param>
        /// <param name="hoursAgo">If &#x60;field&#x60; is session-related, this is *required* to specify the number of hours before or after the user&#39;s session..</param>
        /// <param name="radius">If &#x60;field&#x60; is &#x60;location&#x60;, this will specify the radius in meters from a provided location point. Use with &#x60;lat&#x60; and &#x60;long&#x60;..</param>
        /// <param name="lat">If &#x60;field&#x60; is &#x60;location&#x60;, this is *required* to specify the user&#39;s latitude..</param>
        /// <param name="_long">If &#x60;field&#x60; is &#x60;location&#x60;, this is *required* to specify the user&#39;s longitude..</param>
        /// <param name="relation">Required. Operator of a filter expression..</param>
        public Filter(string field = default(string), string key = default(string), string value = default(string), string hoursAgo = default(string), decimal radius = default(decimal), decimal lat = default(decimal), decimal _long = default(decimal), RelationEnum? relation = default(RelationEnum?))
        {
            this.Field = field;
            this.Key = key;
            this.Value = value;
            this.HoursAgo = hoursAgo;
            this.Radius = radius;
            this.Lat = lat;
            this.Long = _long;
            this.Relation = relation;
        }

        /// <summary>
        /// Required. Name of the field to use as the first operand in the filter expression.
        /// </summary>
        /// <value>Required. Name of the field to use as the first operand in the filter expression.</value>
        [DataMember(Name = "field", EmitDefaultValue = false)]
        public string Field { get; set; }

        /// <summary>
        /// If &#x60;field&#x60; is &#x60;tag&#x60;, this field is *required* to specify &#x60;key&#x60; inside the tags.
        /// </summary>
        /// <value>If &#x60;field&#x60; is &#x60;tag&#x60;, this field is *required* to specify &#x60;key&#x60; inside the tags.</value>
        [DataMember(Name = "key", EmitDefaultValue = false)]
        public string Key { get; set; }

        /// <summary>
        /// Constant value to use as the second operand in the filter expression. This value is *required* when the relation operator is a binary operator.
        /// </summary>
        /// <value>Constant value to use as the second operand in the filter expression. This value is *required* when the relation operator is a binary operator.</value>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public string Value { get; set; }

        /// <summary>
        /// If &#x60;field&#x60; is session-related, this is *required* to specify the number of hours before or after the user&#39;s session.
        /// </summary>
        /// <value>If &#x60;field&#x60; is session-related, this is *required* to specify the number of hours before or after the user&#39;s session.</value>
        [DataMember(Name = "hours_ago", EmitDefaultValue = false)]
        public string HoursAgo { get; set; }

        /// <summary>
        /// If &#x60;field&#x60; is &#x60;location&#x60;, this will specify the radius in meters from a provided location point. Use with &#x60;lat&#x60; and &#x60;long&#x60;.
        /// </summary>
        /// <value>If &#x60;field&#x60; is &#x60;location&#x60;, this will specify the radius in meters from a provided location point. Use with &#x60;lat&#x60; and &#x60;long&#x60;.</value>
        [DataMember(Name = "radius", EmitDefaultValue = false)]
        public decimal Radius { get; set; }

        /// <summary>
        /// If &#x60;field&#x60; is &#x60;location&#x60;, this is *required* to specify the user&#39;s latitude.
        /// </summary>
        /// <value>If &#x60;field&#x60; is &#x60;location&#x60;, this is *required* to specify the user&#39;s latitude.</value>
        [DataMember(Name = "lat", EmitDefaultValue = false)]
        public decimal Lat { get; set; }

        /// <summary>
        /// If &#x60;field&#x60; is &#x60;location&#x60;, this is *required* to specify the user&#39;s longitude.
        /// </summary>
        /// <value>If &#x60;field&#x60; is &#x60;location&#x60;, this is *required* to specify the user&#39;s longitude.</value>
        [DataMember(Name = "long", EmitDefaultValue = false)]
        public decimal Long { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Filter {\n");
            sb.Append("  Field: ").Append(Field).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  HoursAgo: ").Append(HoursAgo).Append("\n");
            sb.Append("  Radius: ").Append(Radius).Append("\n");
            sb.Append("  Lat: ").Append(Lat).Append("\n");
            sb.Append("  Long: ").Append(Long).Append("\n");
            sb.Append("  Relation: ").Append(Relation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Filter);
        }

        /// <summary>
        /// Returns true if Filter instances are equal
        /// </summary>
        /// <param name="input">Instance of Filter to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Filter input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Field == input.Field ||
                    (this.Field != null &&
                    this.Field.Equals(input.Field))
                ) && 
                (
                    this.Key == input.Key ||
                    (this.Key != null &&
                    this.Key.Equals(input.Key))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                ) && 
                (
                    this.HoursAgo == input.HoursAgo ||
                    (this.HoursAgo != null &&
                    this.HoursAgo.Equals(input.HoursAgo))
                ) && 
                (
                    this.Radius == input.Radius ||
                    this.Radius.Equals(input.Radius)
                ) && 
                (
                    this.Lat == input.Lat ||
                    this.Lat.Equals(input.Lat)
                ) && 
                (
                    this.Long == input.Long ||
                    this.Long.Equals(input.Long)
                ) && 
                (
                    this.Relation == input.Relation ||
                    this.Relation.Equals(input.Relation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Field != null)
                {
                    hashCode = (hashCode * 59) + this.Field.GetHashCode();
                }
                if (this.Key != null)
                {
                    hashCode = (hashCode * 59) + this.Key.GetHashCode();
                }
                if (this.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Value.GetHashCode();
                }
                if (this.HoursAgo != null)
                {
                    hashCode = (hashCode * 59) + this.HoursAgo.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Radius.GetHashCode();
                hashCode = (hashCode * 59) + this.Lat.GetHashCode();
                hashCode = (hashCode * 59) + this.Long.GetHashCode();
                hashCode = (hashCode * 59) + this.Relation.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
