/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// JourneyEarlyExitRules
    /// </summary>
    [DataContract(Name = "JourneyEarlyExit_rules")]
    public partial class JourneyEarlyExitRules : IEquatable<JourneyEarlyExitRules>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JourneyEarlyExitRules" /> class.
        /// </summary>
        /// <param name="onSegment">onSegment.</param>
        /// <param name="whenNotInAudience">Exit when the user no longer matches the journey audience. Defaults to false..</param>
        /// <param name="onSession">Exit on a new session start. Defaults to false..</param>
        /// <param name="onEvent">onEvent.</param>
        public JourneyEarlyExitRules(JourneyEarlyExitRulesOnSegment onSegment = default(JourneyEarlyExitRulesOnSegment), bool? whenNotInAudience = default(bool?), bool? onSession = default(bool?), JourneyEarlyExitRulesOnEvent onEvent = default(JourneyEarlyExitRulesOnEvent))
        {
            this.OnSegment = onSegment;
            this.WhenNotInAudience = whenNotInAudience;
            this.OnSession = onSession;
            this.OnEvent = onEvent;
        }

        /// <summary>
        /// Gets or Sets OnSegment
        /// </summary>
        [DataMember(Name = "on_segment", EmitDefaultValue = true)]
        public JourneyEarlyExitRulesOnSegment OnSegment { get; set; }

        /// <summary>
        /// Exit when the user no longer matches the journey audience. Defaults to false.
        /// </summary>
        /// <value>Exit when the user no longer matches the journey audience. Defaults to false.</value>
        [DataMember(Name = "when_not_in_audience", EmitDefaultValue = true)]
        public bool? WhenNotInAudience { get; set; }

        /// <summary>
        /// Exit on a new session start. Defaults to false.
        /// </summary>
        /// <value>Exit on a new session start. Defaults to false.</value>
        [DataMember(Name = "on_session", EmitDefaultValue = true)]
        public bool? OnSession { get; set; }

        /// <summary>
        /// Gets or Sets OnEvent
        /// </summary>
        [DataMember(Name = "on_event", EmitDefaultValue = true)]
        public JourneyEarlyExitRulesOnEvent OnEvent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JourneyEarlyExitRules {\n");
            sb.Append("  OnSegment: ").Append(OnSegment).Append("\n");
            sb.Append("  WhenNotInAudience: ").Append(WhenNotInAudience).Append("\n");
            sb.Append("  OnSession: ").Append(OnSession).Append("\n");
            sb.Append("  OnEvent: ").Append(OnEvent).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JourneyEarlyExitRules);
        }

        /// <summary>
        /// Returns true if JourneyEarlyExitRules instances are equal
        /// </summary>
        /// <param name="input">Instance of JourneyEarlyExitRules to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JourneyEarlyExitRules input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.OnSegment == input.OnSegment ||
                    (this.OnSegment != null &&
                    this.OnSegment.Equals(input.OnSegment))
                ) && 
                (
                    this.WhenNotInAudience == input.WhenNotInAudience ||
                    (this.WhenNotInAudience != null &&
                    this.WhenNotInAudience.Equals(input.WhenNotInAudience))
                ) && 
                (
                    this.OnSession == input.OnSession ||
                    (this.OnSession != null &&
                    this.OnSession.Equals(input.OnSession))
                ) && 
                (
                    this.OnEvent == input.OnEvent ||
                    (this.OnEvent != null &&
                    this.OnEvent.Equals(input.OnEvent))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OnSegment != null)
                {
                    hashCode = (hashCode * 59) + this.OnSegment.GetHashCode();
                }
                if (this.WhenNotInAudience != null)
                {
                    hashCode = (hashCode * 59) + this.WhenNotInAudience.GetHashCode();
                }
                if (this.OnSession != null)
                {
                    hashCode = (hashCode * 59) + this.OnSession.GetHashCode();
                }
                if (this.OnEvent != null)
                {
                    hashCode = (hashCode * 59) + this.OnEvent.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
