/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// A branch condition. The kind field selects which other fields apply.
    /// </summary>
    [DataContract(Name = "JourneyCondition")]
    public partial class JourneyCondition : IEquatable<JourneyCondition>, IValidatableObject
    {
        /// <summary>
        /// Condition kind. Selects which other fields apply.
        /// </summary>
        /// <value>Condition kind. Selects which other fields apply.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum KindEnum
        {
            /// <summary>
            /// Enum SegmentMembership for value: segment_membership
            /// </summary>
            [EnumMember(Value = "segment_membership")]
            SegmentMembership = 1,

            /// <summary>
            /// Enum OnNotificationAction for value: on_notification_action
            /// </summary>
            [EnumMember(Value = "on_notification_action")]
            OnNotificationAction = 2,

            /// <summary>
            /// Enum EventTrigger for value: event_trigger
            /// </summary>
            [EnumMember(Value = "event_trigger")]
            EventTrigger = 3

        }


        /// <summary>
        /// Condition kind. Selects which other fields apply.
        /// </summary>
        /// <value>Condition kind. Selects which other fields apply.</value>
        [DataMember(Name = "kind", IsRequired = true, EmitDefaultValue = false)]
        public KindEnum Kind { get; set; }
        /// <summary>
        /// on_notification_action conditions: the notification action to branch on. Which actions apply depends on the sending node&#39;s channel.
        /// </summary>
        /// <value>on_notification_action conditions: the notification action to branch on. Which actions apply depends on the sending node&#39;s channel.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ActionEnum
        {
            /// <summary>
            /// Enum Received for value: received
            /// </summary>
            [EnumMember(Value = "received")]
            Received = 1,

            /// <summary>
            /// Enum Clicked for value: clicked
            /// </summary>
            [EnumMember(Value = "clicked")]
            Clicked = 2,

            /// <summary>
            /// Enum Opened for value: opened
            /// </summary>
            [EnumMember(Value = "opened")]
            Opened = 3

        }


        /// <summary>
        /// on_notification_action conditions: the notification action to branch on. Which actions apply depends on the sending node&#39;s channel.
        /// </summary>
        /// <value>on_notification_action conditions: the notification action to branch on. Which actions apply depends on the sending node&#39;s channel.</value>
        [DataMember(Name = "action", EmitDefaultValue = false)]
        public ActionEnum? Action { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="JourneyCondition" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected JourneyCondition() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="JourneyCondition" /> class.
        /// </summary>
        /// <param name="kind">Condition kind. Selects which other fields apply. (required).</param>
        /// <param name="includedSegmentIds">segment_membership conditions: Segment UUIDs the user must belong to..</param>
        /// <param name="excludedSegmentIds">segment_membership conditions: Segment UUIDs the user must not belong to..</param>
        /// <param name="action">on_notification_action conditions: the notification action to branch on. Which actions apply depends on the sending node&#39;s channel..</param>
        /// <param name="sendingNodeId">on_notification_action conditions: id of the sending node this action refers to. Returned on reads; accepted on write..</param>
        /// <param name="clientNodeId">on_notification_action conditions: write-only alternative to sending_node_id. References the sending node by its client_node_id..</param>
        /// <param name="name">event_trigger conditions: event name, up to 255 characters..</param>
        /// <param name="attributes">Event attribute matchers, as a list of condition groups. Send a single group whose conditions are AND&#39;d together. More than one group is rejected..</param>
        /// <param name="entryEventMatchAttributes">event_trigger conditions: match incoming event properties against the journey&#39;s entry event. Only valid on event-triggered journeys..</param>
        public JourneyCondition(KindEnum kind = default(KindEnum), List<string> includedSegmentIds = default(List<string>), List<string> excludedSegmentIds = default(List<string>), ActionEnum? action = default(ActionEnum?), string sendingNodeId = default(string), string clientNodeId = default(string), string name = default(string), List<List<JourneyEventAttribute>> attributes = default(List<List<JourneyEventAttribute>>), List<Object> entryEventMatchAttributes = default(List<Object>))
        {
            this.Kind = kind;
            this.IncludedSegmentIds = includedSegmentIds;
            this.ExcludedSegmentIds = excludedSegmentIds;
            this.Action = action;
            this.SendingNodeId = sendingNodeId;
            this.ClientNodeId = clientNodeId;
            this.Name = name;
            this.Attributes = attributes;
            this.EntryEventMatchAttributes = entryEventMatchAttributes;
        }

        /// <summary>
        /// segment_membership conditions: Segment UUIDs the user must belong to.
        /// </summary>
        /// <value>segment_membership conditions: Segment UUIDs the user must belong to.</value>
        [DataMember(Name = "included_segment_ids", EmitDefaultValue = false)]
        public List<string> IncludedSegmentIds { get; set; }

        /// <summary>
        /// segment_membership conditions: Segment UUIDs the user must not belong to.
        /// </summary>
        /// <value>segment_membership conditions: Segment UUIDs the user must not belong to.</value>
        [DataMember(Name = "excluded_segment_ids", EmitDefaultValue = false)]
        public List<string> ExcludedSegmentIds { get; set; }

        /// <summary>
        /// on_notification_action conditions: id of the sending node this action refers to. Returned on reads; accepted on write.
        /// </summary>
        /// <value>on_notification_action conditions: id of the sending node this action refers to. Returned on reads; accepted on write.</value>
        [DataMember(Name = "sending_node_id", EmitDefaultValue = false)]
        public string SendingNodeId { get; set; }

        /// <summary>
        /// on_notification_action conditions: write-only alternative to sending_node_id. References the sending node by its client_node_id.
        /// </summary>
        /// <value>on_notification_action conditions: write-only alternative to sending_node_id. References the sending node by its client_node_id.</value>
        [DataMember(Name = "client_node_id", EmitDefaultValue = false)]
        public string ClientNodeId { get; set; }

        /// <summary>
        /// event_trigger conditions: event name, up to 255 characters.
        /// </summary>
        /// <value>event_trigger conditions: event name, up to 255 characters.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Event attribute matchers, as a list of condition groups. Send a single group whose conditions are AND&#39;d together. More than one group is rejected.
        /// </summary>
        /// <value>Event attribute matchers, as a list of condition groups. Send a single group whose conditions are AND&#39;d together. More than one group is rejected.</value>
        [DataMember(Name = "attributes", EmitDefaultValue = false)]
        public List<List<JourneyEventAttribute>> Attributes { get; set; }

        /// <summary>
        /// event_trigger conditions: match incoming event properties against the journey&#39;s entry event. Only valid on event-triggered journeys.
        /// </summary>
        /// <value>event_trigger conditions: match incoming event properties against the journey&#39;s entry event. Only valid on event-triggered journeys.</value>
        [DataMember(Name = "entry_event_match_attributes", EmitDefaultValue = true)]
        public List<Object> EntryEventMatchAttributes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JourneyCondition {\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  IncludedSegmentIds: ").Append(IncludedSegmentIds).Append("\n");
            sb.Append("  ExcludedSegmentIds: ").Append(ExcludedSegmentIds).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  SendingNodeId: ").Append(SendingNodeId).Append("\n");
            sb.Append("  ClientNodeId: ").Append(ClientNodeId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  EntryEventMatchAttributes: ").Append(EntryEventMatchAttributes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JourneyCondition);
        }

        /// <summary>
        /// Returns true if JourneyCondition instances are equal
        /// </summary>
        /// <param name="input">Instance of JourneyCondition to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JourneyCondition input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Kind == input.Kind ||
                    this.Kind.Equals(input.Kind)
                ) && 
                (
                    this.IncludedSegmentIds == input.IncludedSegmentIds ||
                    this.IncludedSegmentIds != null &&
                    input.IncludedSegmentIds != null &&
                    this.IncludedSegmentIds.SequenceEqual(input.IncludedSegmentIds)
                ) && 
                (
                    this.ExcludedSegmentIds == input.ExcludedSegmentIds ||
                    this.ExcludedSegmentIds != null &&
                    input.ExcludedSegmentIds != null &&
                    this.ExcludedSegmentIds.SequenceEqual(input.ExcludedSegmentIds)
                ) && 
                (
                    this.Action == input.Action ||
                    this.Action.Equals(input.Action)
                ) && 
                (
                    this.SendingNodeId == input.SendingNodeId ||
                    (this.SendingNodeId != null &&
                    this.SendingNodeId.Equals(input.SendingNodeId))
                ) && 
                (
                    this.ClientNodeId == input.ClientNodeId ||
                    (this.ClientNodeId != null &&
                    this.ClientNodeId.Equals(input.ClientNodeId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Attributes == input.Attributes ||
                    this.Attributes != null &&
                    input.Attributes != null &&
                    this.Attributes.SequenceEqual(input.Attributes)
                ) && 
                (
                    this.EntryEventMatchAttributes == input.EntryEventMatchAttributes ||
                    this.EntryEventMatchAttributes != null &&
                    input.EntryEventMatchAttributes != null &&
                    this.EntryEventMatchAttributes.SequenceEqual(input.EntryEventMatchAttributes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Kind.GetHashCode();
                if (this.IncludedSegmentIds != null)
                {
                    hashCode = (hashCode * 59) + this.IncludedSegmentIds.GetHashCode();
                }
                if (this.ExcludedSegmentIds != null)
                {
                    hashCode = (hashCode * 59) + this.ExcludedSegmentIds.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Action.GetHashCode();
                if (this.SendingNodeId != null)
                {
                    hashCode = (hashCode * 59) + this.SendingNodeId.GetHashCode();
                }
                if (this.ClientNodeId != null)
                {
                    hashCode = (hashCode * 59) + this.ClientNodeId.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Attributes != null)
                {
                    hashCode = (hashCode * 59) + this.Attributes.GetHashCode();
                }
                if (this.EntryEventMatchAttributes != null)
                {
                    hashCode = (hashCode * 59) + this.EntryEventMatchAttributes.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
