/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// JourneyTimePoint
    /// </summary>
    [DataContract(Name = "JourneyTimePoint")]
    public partial class JourneyTimePoint : IEquatable<JourneyTimePoint>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JourneyTimePoint" /> class.
        /// </summary>
        /// <param name="hour">Hour of day, 0-23..</param>
        /// <param name="minute">Minute of hour, 0-59. Defaults to 0..</param>
        public JourneyTimePoint(int hour = default(int), int minute = default(int))
        {
            this.Hour = hour;
            this.Minute = minute;
        }

        /// <summary>
        /// Hour of day, 0-23.
        /// </summary>
        /// <value>Hour of day, 0-23.</value>
        [DataMember(Name = "hour", EmitDefaultValue = false)]
        public int Hour { get; set; }

        /// <summary>
        /// Minute of hour, 0-59. Defaults to 0.
        /// </summary>
        /// <value>Minute of hour, 0-59. Defaults to 0.</value>
        [DataMember(Name = "minute", EmitDefaultValue = false)]
        public int Minute { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JourneyTimePoint {\n");
            sb.Append("  Hour: ").Append(Hour).Append("\n");
            sb.Append("  Minute: ").Append(Minute).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JourneyTimePoint);
        }

        /// <summary>
        /// Returns true if JourneyTimePoint instances are equal
        /// </summary>
        /// <param name="input">Instance of JourneyTimePoint to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JourneyTimePoint input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Hour == input.Hour ||
                    this.Hour.Equals(input.Hour)
                ) && 
                (
                    this.Minute == input.Minute ||
                    this.Minute.Equals(input.Minute)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Hour.GetHashCode();
                hashCode = (hashCode * 59) + this.Minute.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // Hour (int) maximum
            if (this.Hour > (int)23)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Hour, must be a value less than or equal to 23.", new [] { "Hour" });
            }

            // Hour (int) minimum
            if (this.Hour < (int)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Hour, must be a value greater than or equal to 0.", new [] { "Hour" });
            }

            // Minute (int) maximum
            if (this.Minute > (int)59)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Minute, must be a value less than or equal to 59.", new [] { "Minute" });
            }

            // Minute (int) minimum
            if (this.Minute < (int)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Minute, must be a value greater than or equal to 0.", new [] { "Minute" });
            }

            yield break;
        }
    }

}
