/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// JourneyEventAttribute
    /// </summary>
    [DataContract(Name = "JourneyEventAttribute")]
    public partial class JourneyEventAttribute : IEquatable<JourneyEventAttribute>, IValidatableObject
    {
        /// <summary>
        /// Comparison operator.
        /// </summary>
        /// <value>Comparison operator.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum OperatorEnum
        {
            /// <summary>
            /// Enum Equal for value: equal
            /// </summary>
            [EnumMember(Value = "equal")]
            Equal = 1,

            /// <summary>
            /// Enum NotEqual for value: not_equal
            /// </summary>
            [EnumMember(Value = "not_equal")]
            NotEqual = 2,

            /// <summary>
            /// Enum Less for value: less
            /// </summary>
            [EnumMember(Value = "less")]
            Less = 3,

            /// <summary>
            /// Enum LessOrEqual for value: less_or_equal
            /// </summary>
            [EnumMember(Value = "less_or_equal")]
            LessOrEqual = 4,

            /// <summary>
            /// Enum GreaterOrEqual for value: greater_or_equal
            /// </summary>
            [EnumMember(Value = "greater_or_equal")]
            GreaterOrEqual = 5,

            /// <summary>
            /// Enum Greater for value: greater
            /// </summary>
            [EnumMember(Value = "greater")]
            Greater = 6,

            /// <summary>
            /// Enum Is for value: is
            /// </summary>
            [EnumMember(Value = "is")]
            Is = 7,

            /// <summary>
            /// Enum IsNot for value: is_not
            /// </summary>
            [EnumMember(Value = "is_not")]
            IsNot = 8,

            /// <summary>
            /// Enum Exists for value: exists
            /// </summary>
            [EnumMember(Value = "exists")]
            Exists = 9,

            /// <summary>
            /// Enum NotExists for value: not_exists
            /// </summary>
            [EnumMember(Value = "not_exists")]
            NotExists = 10,

            /// <summary>
            /// Enum Before for value: before
            /// </summary>
            [EnumMember(Value = "before")]
            Before = 11,

            /// <summary>
            /// Enum After for value: after
            /// </summary>
            [EnumMember(Value = "after")]
            After = 12

        }


        /// <summary>
        /// Comparison operator.
        /// </summary>
        /// <value>Comparison operator.</value>
        [DataMember(Name = "operator", IsRequired = true, EmitDefaultValue = false)]
        public OperatorEnum Operator { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="JourneyEventAttribute" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected JourneyEventAttribute() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="JourneyEventAttribute" /> class.
        /// </summary>
        /// <param name="key">Event attribute key. (required).</param>
        /// <param name="_operator">Comparison operator. (required).</param>
        /// <param name="value">Value to compare against. Not required for exists and not_exists..</param>
        public JourneyEventAttribute(string key = default(string), OperatorEnum _operator = default(OperatorEnum), string value = default(string))
        {
            // to ensure "key" is required (not null)
            if (key == null)
            {
                throw new ArgumentNullException("key is a required property for JourneyEventAttribute and cannot be null");
            }
            this.Key = key;
            this.Operator = _operator;
            this.Value = value;
        }

        /// <summary>
        /// Event attribute key.
        /// </summary>
        /// <value>Event attribute key.</value>
        [DataMember(Name = "key", IsRequired = true, EmitDefaultValue = false)]
        public string Key { get; set; }

        /// <summary>
        /// Value to compare against. Not required for exists and not_exists.
        /// </summary>
        /// <value>Value to compare against. Not required for exists and not_exists.</value>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JourneyEventAttribute {\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  Operator: ").Append(Operator).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JourneyEventAttribute);
        }

        /// <summary>
        /// Returns true if JourneyEventAttribute instances are equal
        /// </summary>
        /// <param name="input">Instance of JourneyEventAttribute to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JourneyEventAttribute input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Key == input.Key ||
                    (this.Key != null &&
                    this.Key.Equals(input.Key))
                ) && 
                (
                    this.Operator == input.Operator ||
                    this.Operator.Equals(input.Operator)
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Key != null)
                {
                    hashCode = (hashCode * 59) + this.Key.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Operator.GetHashCode();
                if (this.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Value.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
