/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// Stats for a single branch of a branching node. Keyed in the response by the branch&#39;s server-assigned id.
    /// </summary>
    [DataContract(Name = "JourneyBranchStats")]
    public partial class JourneyBranchStats : IEquatable<JourneyBranchStats>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JourneyBranchStats" /> class.
        /// </summary>
        /// <param name="completed">Users who took this branch..</param>
        public JourneyBranchStats(int completed = default(int))
        {
            this.Completed = completed;
        }

        /// <summary>
        /// Users who took this branch.
        /// </summary>
        /// <value>Users who took this branch.</value>
        [DataMember(Name = "completed", EmitDefaultValue = false)]
        public int Completed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JourneyBranchStats {\n");
            sb.Append("  Completed: ").Append(Completed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JourneyBranchStats);
        }

        /// <summary>
        /// Returns true if JourneyBranchStats instances are equal
        /// </summary>
        /// <param name="input">Instance of JourneyBranchStats to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JourneyBranchStats input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Completed == input.Completed ||
                    this.Completed.Equals(input.Completed)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Completed.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
