/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// The journey entry audience. The kind field selects which other fields apply.
    /// </summary>
    [DataContract(Name = "JourneyAudience")]
    public partial class JourneyAudience : IEquatable<JourneyAudience>, IValidatableObject
    {
        /// <summary>
        /// Audience kind. Selects which other fields apply.
        /// </summary>
        /// <value>Audience kind. Selects which other fields apply.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum KindEnum
        {
            /// <summary>
            /// Enum Segment for value: segment
            /// </summary>
            [EnumMember(Value = "segment")]
            Segment = 1,

            /// <summary>
            /// Enum EventTrigger for value: event_trigger
            /// </summary>
            [EnumMember(Value = "event_trigger")]
            EventTrigger = 2

        }


        /// <summary>
        /// Audience kind. Selects which other fields apply.
        /// </summary>
        /// <value>Audience kind. Selects which other fields apply.</value>
        [DataMember(Name = "kind", IsRequired = true, EmitDefaultValue = false)]
        public KindEnum Kind { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="JourneyAudience" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected JourneyAudience() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="JourneyAudience" /> class.
        /// </summary>
        /// <param name="kind">Audience kind. Selects which other fields apply. (required).</param>
        /// <param name="includedSegmentIds">segment audiences: Segment UUIDs whose users enter the journey..</param>
        /// <param name="excludedSegmentIds">segment audiences: Segment UUIDs whose users are excluded..</param>
        /// <param name="futureAdditionsOnly">segment audiences: when true, only users who newly match the segment after activation enter the journey. Defaults to false..</param>
        /// <param name="name">event_trigger audiences: event name that triggers entry, up to 255 characters..</param>
        /// <param name="attributes">Event attribute matchers, as a list of condition groups. Send a single group whose conditions are AND&#39;d together. More than one group is rejected..</param>
        public JourneyAudience(KindEnum kind = default(KindEnum), List<string> includedSegmentIds = default(List<string>), List<string> excludedSegmentIds = default(List<string>), bool? futureAdditionsOnly = default(bool?), string name = default(string), List<List<JourneyEventAttribute>> attributes = default(List<List<JourneyEventAttribute>>))
        {
            this.Kind = kind;
            this.IncludedSegmentIds = includedSegmentIds;
            this.ExcludedSegmentIds = excludedSegmentIds;
            this.FutureAdditionsOnly = futureAdditionsOnly;
            this.Name = name;
            this.Attributes = attributes;
        }

        /// <summary>
        /// segment audiences: Segment UUIDs whose users enter the journey.
        /// </summary>
        /// <value>segment audiences: Segment UUIDs whose users enter the journey.</value>
        [DataMember(Name = "included_segment_ids", EmitDefaultValue = false)]
        public List<string> IncludedSegmentIds { get; set; }

        /// <summary>
        /// segment audiences: Segment UUIDs whose users are excluded.
        /// </summary>
        /// <value>segment audiences: Segment UUIDs whose users are excluded.</value>
        [DataMember(Name = "excluded_segment_ids", EmitDefaultValue = false)]
        public List<string> ExcludedSegmentIds { get; set; }

        /// <summary>
        /// segment audiences: when true, only users who newly match the segment after activation enter the journey. Defaults to false.
        /// </summary>
        /// <value>segment audiences: when true, only users who newly match the segment after activation enter the journey. Defaults to false.</value>
        [DataMember(Name = "future_additions_only", EmitDefaultValue = true)]
        public bool? FutureAdditionsOnly { get; set; }

        /// <summary>
        /// event_trigger audiences: event name that triggers entry, up to 255 characters.
        /// </summary>
        /// <value>event_trigger audiences: event name that triggers entry, up to 255 characters.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Event attribute matchers, as a list of condition groups. Send a single group whose conditions are AND&#39;d together. More than one group is rejected.
        /// </summary>
        /// <value>Event attribute matchers, as a list of condition groups. Send a single group whose conditions are AND&#39;d together. More than one group is rejected.</value>
        [DataMember(Name = "attributes", EmitDefaultValue = false)]
        public List<List<JourneyEventAttribute>> Attributes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JourneyAudience {\n");
            sb.Append("  Kind: ").Append(Kind).Append("\n");
            sb.Append("  IncludedSegmentIds: ").Append(IncludedSegmentIds).Append("\n");
            sb.Append("  ExcludedSegmentIds: ").Append(ExcludedSegmentIds).Append("\n");
            sb.Append("  FutureAdditionsOnly: ").Append(FutureAdditionsOnly).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JourneyAudience);
        }

        /// <summary>
        /// Returns true if JourneyAudience instances are equal
        /// </summary>
        /// <param name="input">Instance of JourneyAudience to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JourneyAudience input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Kind == input.Kind ||
                    this.Kind.Equals(input.Kind)
                ) && 
                (
                    this.IncludedSegmentIds == input.IncludedSegmentIds ||
                    this.IncludedSegmentIds != null &&
                    input.IncludedSegmentIds != null &&
                    this.IncludedSegmentIds.SequenceEqual(input.IncludedSegmentIds)
                ) && 
                (
                    this.ExcludedSegmentIds == input.ExcludedSegmentIds ||
                    this.ExcludedSegmentIds != null &&
                    input.ExcludedSegmentIds != null &&
                    this.ExcludedSegmentIds.SequenceEqual(input.ExcludedSegmentIds)
                ) && 
                (
                    this.FutureAdditionsOnly == input.FutureAdditionsOnly ||
                    (this.FutureAdditionsOnly != null &&
                    this.FutureAdditionsOnly.Equals(input.FutureAdditionsOnly))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Attributes == input.Attributes ||
                    this.Attributes != null &&
                    input.Attributes != null &&
                    this.Attributes.SequenceEqual(input.Attributes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Kind.GetHashCode();
                if (this.IncludedSegmentIds != null)
                {
                    hashCode = (hashCode * 59) + this.IncludedSegmentIds.GetHashCode();
                }
                if (this.ExcludedSegmentIds != null)
                {
                    hashCode = (hashCode * 59) + this.ExcludedSegmentIds.GetHashCode();
                }
                if (this.FutureAdditionsOnly != null)
                {
                    hashCode = (hashCode * 59) + this.FutureAdditionsOnly.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Attributes != null)
                {
                    hashCode = (hashCode * 59) + this.Attributes.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
