/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// Controls whether and how soon a user can re-enter the journey. null means re-entry is not allowed.
    /// </summary>
    [DataContract(Name = "JourneyReentryRules")]
    public partial class JourneyReentryRules : IEquatable<JourneyReentryRules>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JourneyReentryRules" /> class.
        /// </summary>
        /// <param name="durationSeconds">Minimum seconds before a user can re-enter. Must be at least 600 (10 minutes)..</param>
        public JourneyReentryRules(int? durationSeconds = default(int?))
        {
            this.DurationSeconds = durationSeconds;
        }

        /// <summary>
        /// Minimum seconds before a user can re-enter. Must be at least 600 (10 minutes).
        /// </summary>
        /// <value>Minimum seconds before a user can re-enter. Must be at least 600 (10 minutes).</value>
        [DataMember(Name = "duration_seconds", EmitDefaultValue = true)]
        public int? DurationSeconds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JourneyReentryRules {\n");
            sb.Append("  DurationSeconds: ").Append(DurationSeconds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JourneyReentryRules);
        }

        /// <summary>
        /// Returns true if JourneyReentryRules instances are equal
        /// </summary>
        /// <param name="input">Instance of JourneyReentryRules to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JourneyReentryRules input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.DurationSeconds == input.DurationSeconds ||
                    (this.DurationSeconds != null &&
                    this.DurationSeconds.Equals(input.DurationSeconds))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DurationSeconds != null)
                {
                    hashCode = (hashCode * 59) + this.DurationSeconds.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // DurationSeconds (int?) minimum
            if (this.DurationSeconds < (int?)600)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DurationSeconds, must be a value greater than or equal to 600.", new [] { "DurationSeconds" });
            }

            yield break;
        }
    }

}
