/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// JourneyListResponse
    /// </summary>
    [DataContract(Name = "JourneyListResponse")]
    public partial class JourneyListResponse : IEquatable<JourneyListResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JourneyListResponse" /> class.
        /// </summary>
        /// <param name="journeys">Journeys ordered by creation time, newest first..</param>
        /// <param name="hasMore">true if more journeys exist beyond this page..</param>
        /// <param name="nextCursor">Cursor for the next page. Present only when has_more is true..</param>
        public JourneyListResponse(List<JourneyListItem> journeys = default(List<JourneyListItem>), bool hasMore = default(bool), string nextCursor = default(string))
        {
            this.Journeys = journeys;
            this.HasMore = hasMore;
            this.NextCursor = nextCursor;
        }

        /// <summary>
        /// Journeys ordered by creation time, newest first.
        /// </summary>
        /// <value>Journeys ordered by creation time, newest first.</value>
        [DataMember(Name = "journeys", EmitDefaultValue = false)]
        public List<JourneyListItem> Journeys { get; set; }

        /// <summary>
        /// true if more journeys exist beyond this page.
        /// </summary>
        /// <value>true if more journeys exist beyond this page.</value>
        [DataMember(Name = "has_more", EmitDefaultValue = true)]
        public bool HasMore { get; set; }

        /// <summary>
        /// Cursor for the next page. Present only when has_more is true.
        /// </summary>
        /// <value>Cursor for the next page. Present only when has_more is true.</value>
        [DataMember(Name = "next_cursor", EmitDefaultValue = false)]
        public string NextCursor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JourneyListResponse {\n");
            sb.Append("  Journeys: ").Append(Journeys).Append("\n");
            sb.Append("  HasMore: ").Append(HasMore).Append("\n");
            sb.Append("  NextCursor: ").Append(NextCursor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JourneyListResponse);
        }

        /// <summary>
        /// Returns true if JourneyListResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of JourneyListResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JourneyListResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Journeys == input.Journeys ||
                    this.Journeys != null &&
                    input.Journeys != null &&
                    this.Journeys.SequenceEqual(input.Journeys)
                ) && 
                (
                    this.HasMore == input.HasMore ||
                    this.HasMore.Equals(input.HasMore)
                ) && 
                (
                    this.NextCursor == input.NextCursor ||
                    (this.NextCursor != null &&
                    this.NextCursor.Equals(input.NextCursor))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Journeys != null)
                {
                    hashCode = (hashCode * 59) + this.Journeys.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.HasMore.GetHashCode();
                if (this.NextCursor != null)
                {
                    hashCode = (hashCode * 59) + this.NextCursor.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
