/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// Summary journey representation returned by the list endpoint. Excludes description, nodes, early-exit configuration, and concurrency_key.
    /// </summary>
    [DataContract(Name = "JourneyListItem")]
    public partial class JourneyListItem : IEquatable<JourneyListItem>, IValidatableObject
    {
        /// <summary>
        /// Journey state. New journeys are created as draft. processing is transient while activation is in progress. archived is a journey that has been stopped. Change it through the state field on Update journey.
        /// </summary>
        /// <value>Journey state. New journeys are created as draft. processing is transient while activation is in progress. archived is a journey that has been stopped. Change it through the state field on Update journey.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StateEnum
        {
            /// <summary>
            /// Enum Draft for value: draft
            /// </summary>
            [EnumMember(Value = "draft")]
            Draft = 1,

            /// <summary>
            /// Enum Scheduled for value: scheduled
            /// </summary>
            [EnumMember(Value = "scheduled")]
            Scheduled = 2,

            /// <summary>
            /// Enum Processing for value: processing
            /// </summary>
            [EnumMember(Value = "processing")]
            Processing = 3,

            /// <summary>
            /// Enum Active for value: active
            /// </summary>
            [EnumMember(Value = "active")]
            Active = 4,

            /// <summary>
            /// Enum Archived for value: archived
            /// </summary>
            [EnumMember(Value = "archived")]
            Archived = 5

        }


        /// <summary>
        /// Journey state. New journeys are created as draft. processing is transient while activation is in progress. archived is a journey that has been stopped. Change it through the state field on Update journey.
        /// </summary>
        /// <value>Journey state. New journeys are created as draft. processing is transient while activation is in progress. archived is a journey that has been stopped. Change it through the state field on Update journey.</value>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public StateEnum? State { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="JourneyListItem" /> class.
        /// </summary>
        /// <param name="id">Journey UUID. Read-only..</param>
        /// <param name="appId">UUID of the app the journey belongs to. Read-only..</param>
        /// <param name="name">Journey name, up to 300 characters..</param>
        /// <param name="state">Journey state. New journeys are created as draft. processing is transient while activation is in progress. archived is a journey that has been stopped. Change it through the state field on Update journey..</param>
        /// <param name="createdAt">ISO 8601 creation time. Read-only..</param>
        /// <param name="updatedAt">ISO 8601 last-update time. Read-only..</param>
        /// <param name="startedAt">ISO 8601 time the journey was activated, or null. Read-only..</param>
        /// <param name="archivedAt">ISO 8601 time the journey was archived, or null. Read-only..</param>
        /// <param name="createdSource">Origin of the journey, for example public_api or dashboard. Read-only..</param>
        /// <param name="schedule">schedule.</param>
        /// <param name="audience">audience.</param>
        /// <param name="reentryRules">reentryRules.</param>
        public JourneyListItem(string id = default(string), string appId = default(string), string name = default(string), StateEnum? state = default(StateEnum?), string createdAt = default(string), string updatedAt = default(string), string startedAt = default(string), string archivedAt = default(string), string createdSource = default(string), JourneySchedule schedule = default(JourneySchedule), JourneyListAudience audience = default(JourneyListAudience), JourneyReentryRules reentryRules = default(JourneyReentryRules))
        {
            this.Id = id;
            this.AppId = appId;
            this.Name = name;
            this.State = state;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.StartedAt = startedAt;
            this.ArchivedAt = archivedAt;
            this.CreatedSource = createdSource;
            this.Schedule = schedule;
            this.Audience = audience;
            this.ReentryRules = reentryRules;
        }

        /// <summary>
        /// Journey UUID. Read-only.
        /// </summary>
        /// <value>Journey UUID. Read-only.</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// UUID of the app the journey belongs to. Read-only.
        /// </summary>
        /// <value>UUID of the app the journey belongs to. Read-only.</value>
        [DataMember(Name = "app_id", EmitDefaultValue = false)]
        public string AppId { get; set; }

        /// <summary>
        /// Journey name, up to 300 characters.
        /// </summary>
        /// <value>Journey name, up to 300 characters.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// ISO 8601 creation time. Read-only.
        /// </summary>
        /// <value>ISO 8601 creation time. Read-only.</value>
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// ISO 8601 last-update time. Read-only.
        /// </summary>
        /// <value>ISO 8601 last-update time. Read-only.</value>
        [DataMember(Name = "updated_at", EmitDefaultValue = false)]
        public string UpdatedAt { get; set; }

        /// <summary>
        /// ISO 8601 time the journey was activated, or null. Read-only.
        /// </summary>
        /// <value>ISO 8601 time the journey was activated, or null. Read-only.</value>
        [DataMember(Name = "started_at", EmitDefaultValue = true)]
        public string StartedAt { get; set; }

        /// <summary>
        /// ISO 8601 time the journey was archived, or null. Read-only.
        /// </summary>
        /// <value>ISO 8601 time the journey was archived, or null. Read-only.</value>
        [DataMember(Name = "archived_at", EmitDefaultValue = true)]
        public string ArchivedAt { get; set; }

        /// <summary>
        /// Origin of the journey, for example public_api or dashboard. Read-only.
        /// </summary>
        /// <value>Origin of the journey, for example public_api or dashboard. Read-only.</value>
        [DataMember(Name = "created_source", EmitDefaultValue = true)]
        public string CreatedSource { get; set; }

        /// <summary>
        /// Gets or Sets Schedule
        /// </summary>
        [DataMember(Name = "schedule", EmitDefaultValue = true)]
        public JourneySchedule Schedule { get; set; }

        /// <summary>
        /// Gets or Sets Audience
        /// </summary>
        [DataMember(Name = "audience", EmitDefaultValue = false)]
        public JourneyListAudience Audience { get; set; }

        /// <summary>
        /// Gets or Sets ReentryRules
        /// </summary>
        [DataMember(Name = "reentry_rules", EmitDefaultValue = true)]
        public JourneyReentryRules ReentryRules { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JourneyListItem {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  AppId: ").Append(AppId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("  StartedAt: ").Append(StartedAt).Append("\n");
            sb.Append("  ArchivedAt: ").Append(ArchivedAt).Append("\n");
            sb.Append("  CreatedSource: ").Append(CreatedSource).Append("\n");
            sb.Append("  Schedule: ").Append(Schedule).Append("\n");
            sb.Append("  Audience: ").Append(Audience).Append("\n");
            sb.Append("  ReentryRules: ").Append(ReentryRules).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as JourneyListItem);
        }

        /// <summary>
        /// Returns true if JourneyListItem instances are equal
        /// </summary>
        /// <param name="input">Instance of JourneyListItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(JourneyListItem input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.AppId == input.AppId ||
                    (this.AppId != null &&
                    this.AppId.Equals(input.AppId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.State == input.State ||
                    this.State.Equals(input.State)
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.UpdatedAt == input.UpdatedAt ||
                    (this.UpdatedAt != null &&
                    this.UpdatedAt.Equals(input.UpdatedAt))
                ) && 
                (
                    this.StartedAt == input.StartedAt ||
                    (this.StartedAt != null &&
                    this.StartedAt.Equals(input.StartedAt))
                ) && 
                (
                    this.ArchivedAt == input.ArchivedAt ||
                    (this.ArchivedAt != null &&
                    this.ArchivedAt.Equals(input.ArchivedAt))
                ) && 
                (
                    this.CreatedSource == input.CreatedSource ||
                    (this.CreatedSource != null &&
                    this.CreatedSource.Equals(input.CreatedSource))
                ) && 
                (
                    this.Schedule == input.Schedule ||
                    (this.Schedule != null &&
                    this.Schedule.Equals(input.Schedule))
                ) && 
                (
                    this.Audience == input.Audience ||
                    (this.Audience != null &&
                    this.Audience.Equals(input.Audience))
                ) && 
                (
                    this.ReentryRules == input.ReentryRules ||
                    (this.ReentryRules != null &&
                    this.ReentryRules.Equals(input.ReentryRules))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.AppId != null)
                {
                    hashCode = (hashCode * 59) + this.AppId.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.State.GetHashCode();
                if (this.CreatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedAt.GetHashCode();
                }
                if (this.UpdatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.UpdatedAt.GetHashCode();
                }
                if (this.StartedAt != null)
                {
                    hashCode = (hashCode * 59) + this.StartedAt.GetHashCode();
                }
                if (this.ArchivedAt != null)
                {
                    hashCode = (hashCode * 59) + this.ArchivedAt.GetHashCode();
                }
                if (this.CreatedSource != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedSource.GetHashCode();
                }
                if (this.Schedule != null)
                {
                    hashCode = (hashCode * 59) + this.Schedule.GetHashCode();
                }
                if (this.Audience != null)
                {
                    hashCode = (hashCode * 59) + this.Audience.GetHashCode();
                }
                if (this.ReentryRules != null)
                {
                    hashCode = (hashCode * 59) + this.ReentryRules.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
