/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// StartLiveActivityRequest
    /// </summary>
    [DataContract(Name = "StartLiveActivityRequest")]
    public partial class StartLiveActivityRequest : IEquatable<StartLiveActivityRequest>, IValidatableObject
    {
        /// <summary>
        /// Defines Event
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum EventEnum
        {
            /// <summary>
            /// Enum Start for value: start
            /// </summary>
            [EnumMember(Value = "start")]
            Start = 1

        }


        /// <summary>
        /// Gets or Sets Event
        /// </summary>
        [DataMember(Name = "event", IsRequired = true, EmitDefaultValue = false)]
        public EventEnum Event { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="StartLiveActivityRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StartLiveActivityRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StartLiveActivityRequest" /> class.
        /// </summary>
        /// <param name="name">An internal name to assist with your campaign organization. This does not get displayed in the message itself. (required).</param>
        /// <param name="_event">_event (required) (default to EventEnum.Start).</param>
        /// <param name="activityId">Set a unique activity_id to track and manage the Live Activity. (required).</param>
        /// <param name="eventAttributes">Default/static data to initialize the Live Activity upon start. (required).</param>
        /// <param name="eventUpdates">Dynamic content used to update the running Live Activity at start. Must match the ContentState interface defined in your app. (required).</param>
        /// <param name="contents">contents (required).</param>
        /// <param name="headings">headings (required).</param>
        /// <param name="staleDate">Accepts Unix timestamp in seconds. When time reaches the configured stale date, the system considers the Live Activity out of date, and the ActivityState of the Live Activity changes to ActivityState.stale..</param>
        /// <param name="priority">Delivery priority through the push provider (APNs). Pass 10 for higher priority notifications, or 5 for lower priority notifications. Lower priority notifications are sent based on the power considerations of the end user&#39;s device. If not set, defaults to 10..</param>
        /// <param name="iosRelevanceScore">iOS 15+. A score to indicate how a notification should be displayed when grouped. Use a float between 0-1..</param>
        /// <param name="idempotencyKey">Correlation and idempotency key. A request received with this parameter will first look for another notification with the same idempotency key. If one exists, a notification will not be sent, and result of the previous operation will instead be returned. Therefore, if you plan on using this feature, it&#39;s important to use a good source of randomness to generate the UUID passed here. This key is only idempotent for 30 days. After 30 days, the notification could be removed from our system and a notification with the same idempotency key will be sent again.   See Idempotent Notification Requests for more details writeOnly: true .</param>
        /// <param name="includeAliases">Target specific users by aliases assigned via API. An alias can be an external_id, onesignal_id, or a custom alias. Accepts an object where keys are alias labels and values are arrays of alias IDs to include Example usage: { \&quot;external_id\&quot;: [\&quot;exId1\&quot;, \&quot;extId2\&quot;], \&quot;internal_label\&quot;: [\&quot;id1\&quot;, \&quot;id2\&quot;] } Not compatible with any other targeting parameters. REQUIRED: REST API Key Authentication Limit of 2,000 entries per REST API call Note: If targeting push, email, or sms subscribers with same ids, use with target_channel to indicate you are sending a push or email or sms..</param>
        /// <param name="includeSubscriptionIds">Specific subscription ids to target. Not compatible with other targeting parameters..</param>
        /// <param name="includedSegments">Segment names to include. Only compatible with excluded_segments..</param>
        /// <param name="excludedSegments">Segment names to exclude. Only compatible with included_segments..</param>
        /// <param name="filters">filters.</param>
        public StartLiveActivityRequest(string name = default(string), EventEnum _event = EventEnum.Start, string activityId = default(string), Object eventAttributes = default(Object), Object eventUpdates = default(Object), LanguageStringMap contents = default(LanguageStringMap), LanguageStringMap headings = default(LanguageStringMap), int staleDate = default(int), int priority = default(int), decimal? iosRelevanceScore = default(decimal?), string idempotencyKey = default(string), Dictionary<string, List<string>> includeAliases = default(Dictionary<string, List<string>>), List<string> includeSubscriptionIds = default(List<string>), List<string> includedSegments = default(List<string>), List<string> excludedSegments = default(List<string>), List<FilterExpression> filters = default(List<FilterExpression>))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for StartLiveActivityRequest and cannot be null");
            }
            this.Name = name;
            this.Event = _event;
            // to ensure "activityId" is required (not null)
            if (activityId == null)
            {
                throw new ArgumentNullException("activityId is a required property for StartLiveActivityRequest and cannot be null");
            }
            this.ActivityId = activityId;
            // to ensure "eventAttributes" is required (not null)
            if (eventAttributes == null)
            {
                throw new ArgumentNullException("eventAttributes is a required property for StartLiveActivityRequest and cannot be null");
            }
            this.EventAttributes = eventAttributes;
            // to ensure "eventUpdates" is required (not null)
            if (eventUpdates == null)
            {
                throw new ArgumentNullException("eventUpdates is a required property for StartLiveActivityRequest and cannot be null");
            }
            this.EventUpdates = eventUpdates;
            // to ensure "contents" is required (not null)
            if (contents == null)
            {
                throw new ArgumentNullException("contents is a required property for StartLiveActivityRequest and cannot be null");
            }
            this.Contents = contents;
            // to ensure "headings" is required (not null)
            if (headings == null)
            {
                throw new ArgumentNullException("headings is a required property for StartLiveActivityRequest and cannot be null");
            }
            this.Headings = headings;
            this.StaleDate = staleDate;
            this.Priority = priority;
            this.IosRelevanceScore = iosRelevanceScore;
            this.IdempotencyKey = idempotencyKey;
            this.IncludeAliases = includeAliases;
            this.IncludeSubscriptionIds = includeSubscriptionIds;
            this.IncludedSegments = includedSegments;
            this.ExcludedSegments = excludedSegments;
            this.Filters = filters;
        }

        /// <summary>
        /// An internal name to assist with your campaign organization. This does not get displayed in the message itself.
        /// </summary>
        /// <value>An internal name to assist with your campaign organization. This does not get displayed in the message itself.</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Set a unique activity_id to track and manage the Live Activity.
        /// </summary>
        /// <value>Set a unique activity_id to track and manage the Live Activity.</value>
        [DataMember(Name = "activity_id", IsRequired = true, EmitDefaultValue = false)]
        public string ActivityId { get; set; }

        /// <summary>
        /// Default/static data to initialize the Live Activity upon start.
        /// </summary>
        /// <value>Default/static data to initialize the Live Activity upon start.</value>
        [DataMember(Name = "event_attributes", IsRequired = true, EmitDefaultValue = false)]
        public Object EventAttributes { get; set; }

        /// <summary>
        /// Dynamic content used to update the running Live Activity at start. Must match the ContentState interface defined in your app.
        /// </summary>
        /// <value>Dynamic content used to update the running Live Activity at start. Must match the ContentState interface defined in your app.</value>
        [DataMember(Name = "event_updates", IsRequired = true, EmitDefaultValue = false)]
        public Object EventUpdates { get; set; }

        /// <summary>
        /// Gets or Sets Contents
        /// </summary>
        [DataMember(Name = "contents", IsRequired = true, EmitDefaultValue = false)]
        public LanguageStringMap Contents { get; set; }

        /// <summary>
        /// Gets or Sets Headings
        /// </summary>
        [DataMember(Name = "headings", IsRequired = true, EmitDefaultValue = false)]
        public LanguageStringMap Headings { get; set; }

        /// <summary>
        /// Accepts Unix timestamp in seconds. When time reaches the configured stale date, the system considers the Live Activity out of date, and the ActivityState of the Live Activity changes to ActivityState.stale.
        /// </summary>
        /// <value>Accepts Unix timestamp in seconds. When time reaches the configured stale date, the system considers the Live Activity out of date, and the ActivityState of the Live Activity changes to ActivityState.stale.</value>
        [DataMember(Name = "stale_date", EmitDefaultValue = false)]
        public int StaleDate { get; set; }

        /// <summary>
        /// Delivery priority through the push provider (APNs). Pass 10 for higher priority notifications, or 5 for lower priority notifications. Lower priority notifications are sent based on the power considerations of the end user&#39;s device. If not set, defaults to 10.
        /// </summary>
        /// <value>Delivery priority through the push provider (APNs). Pass 10 for higher priority notifications, or 5 for lower priority notifications. Lower priority notifications are sent based on the power considerations of the end user&#39;s device. If not set, defaults to 10.</value>
        [DataMember(Name = "priority", EmitDefaultValue = false)]
        public int Priority { get; set; }

        /// <summary>
        /// iOS 15+. A score to indicate how a notification should be displayed when grouped. Use a float between 0-1.
        /// </summary>
        /// <value>iOS 15+. A score to indicate how a notification should be displayed when grouped. Use a float between 0-1.</value>
        [DataMember(Name = "ios_relevance_score", EmitDefaultValue = true)]
        public decimal? IosRelevanceScore { get; set; }

        /// <summary>
        /// Correlation and idempotency key. A request received with this parameter will first look for another notification with the same idempotency key. If one exists, a notification will not be sent, and result of the previous operation will instead be returned. Therefore, if you plan on using this feature, it&#39;s important to use a good source of randomness to generate the UUID passed here. This key is only idempotent for 30 days. After 30 days, the notification could be removed from our system and a notification with the same idempotency key will be sent again.   See Idempotent Notification Requests for more details writeOnly: true 
        /// </summary>
        /// <value>Correlation and idempotency key. A request received with this parameter will first look for another notification with the same idempotency key. If one exists, a notification will not be sent, and result of the previous operation will instead be returned. Therefore, if you plan on using this feature, it&#39;s important to use a good source of randomness to generate the UUID passed here. This key is only idempotent for 30 days. After 30 days, the notification could be removed from our system and a notification with the same idempotency key will be sent again.   See Idempotent Notification Requests for more details writeOnly: true </value>
        [DataMember(Name = "idempotency_key", EmitDefaultValue = true)]
        public string IdempotencyKey { get; set; }

        /// <summary>
        /// Target specific users by aliases assigned via API. An alias can be an external_id, onesignal_id, or a custom alias. Accepts an object where keys are alias labels and values are arrays of alias IDs to include Example usage: { \&quot;external_id\&quot;: [\&quot;exId1\&quot;, \&quot;extId2\&quot;], \&quot;internal_label\&quot;: [\&quot;id1\&quot;, \&quot;id2\&quot;] } Not compatible with any other targeting parameters. REQUIRED: REST API Key Authentication Limit of 2,000 entries per REST API call Note: If targeting push, email, or sms subscribers with same ids, use with target_channel to indicate you are sending a push or email or sms.
        /// </summary>
        /// <value>Target specific users by aliases assigned via API. An alias can be an external_id, onesignal_id, or a custom alias. Accepts an object where keys are alias labels and values are arrays of alias IDs to include Example usage: { \&quot;external_id\&quot;: [\&quot;exId1\&quot;, \&quot;extId2\&quot;], \&quot;internal_label\&quot;: [\&quot;id1\&quot;, \&quot;id2\&quot;] } Not compatible with any other targeting parameters. REQUIRED: REST API Key Authentication Limit of 2,000 entries per REST API call Note: If targeting push, email, or sms subscribers with same ids, use with target_channel to indicate you are sending a push or email or sms.</value>
        [DataMember(Name = "include_aliases", EmitDefaultValue = true)]
        public Dictionary<string, List<string>> IncludeAliases { get; set; }

        /// <summary>
        /// Specific subscription ids to target. Not compatible with other targeting parameters.
        /// </summary>
        /// <value>Specific subscription ids to target. Not compatible with other targeting parameters.</value>
        [DataMember(Name = "include_subscription_ids", EmitDefaultValue = true)]
        public List<string> IncludeSubscriptionIds { get; set; }

        /// <summary>
        /// Segment names to include. Only compatible with excluded_segments.
        /// </summary>
        /// <value>Segment names to include. Only compatible with excluded_segments.</value>
        [DataMember(Name = "included_segments", EmitDefaultValue = true)]
        public List<string> IncludedSegments { get; set; }

        /// <summary>
        /// Segment names to exclude. Only compatible with included_segments.
        /// </summary>
        /// <value>Segment names to exclude. Only compatible with included_segments.</value>
        [DataMember(Name = "excluded_segments", EmitDefaultValue = true)]
        public List<string> ExcludedSegments { get; set; }

        /// <summary>
        /// Gets or Sets Filters
        /// </summary>
        [DataMember(Name = "filters", EmitDefaultValue = true)]
        public List<FilterExpression> Filters { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StartLiveActivityRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Event: ").Append(Event).Append("\n");
            sb.Append("  ActivityId: ").Append(ActivityId).Append("\n");
            sb.Append("  EventAttributes: ").Append(EventAttributes).Append("\n");
            sb.Append("  EventUpdates: ").Append(EventUpdates).Append("\n");
            sb.Append("  Contents: ").Append(Contents).Append("\n");
            sb.Append("  Headings: ").Append(Headings).Append("\n");
            sb.Append("  StaleDate: ").Append(StaleDate).Append("\n");
            sb.Append("  Priority: ").Append(Priority).Append("\n");
            sb.Append("  IosRelevanceScore: ").Append(IosRelevanceScore).Append("\n");
            sb.Append("  IdempotencyKey: ").Append(IdempotencyKey).Append("\n");
            sb.Append("  IncludeAliases: ").Append(IncludeAliases).Append("\n");
            sb.Append("  IncludeSubscriptionIds: ").Append(IncludeSubscriptionIds).Append("\n");
            sb.Append("  IncludedSegments: ").Append(IncludedSegments).Append("\n");
            sb.Append("  ExcludedSegments: ").Append(ExcludedSegments).Append("\n");
            sb.Append("  Filters: ").Append(Filters).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StartLiveActivityRequest);
        }

        /// <summary>
        /// Returns true if StartLiveActivityRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of StartLiveActivityRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StartLiveActivityRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Event == input.Event ||
                    this.Event.Equals(input.Event)
                ) && 
                (
                    this.ActivityId == input.ActivityId ||
                    (this.ActivityId != null &&
                    this.ActivityId.Equals(input.ActivityId))
                ) && 
                (
                    this.EventAttributes == input.EventAttributes ||
                    (this.EventAttributes != null &&
                    this.EventAttributes.Equals(input.EventAttributes))
                ) && 
                (
                    this.EventUpdates == input.EventUpdates ||
                    (this.EventUpdates != null &&
                    this.EventUpdates.Equals(input.EventUpdates))
                ) && 
                (
                    this.Contents == input.Contents ||
                    (this.Contents != null &&
                    this.Contents.Equals(input.Contents))
                ) && 
                (
                    this.Headings == input.Headings ||
                    (this.Headings != null &&
                    this.Headings.Equals(input.Headings))
                ) && 
                (
                    this.StaleDate == input.StaleDate ||
                    this.StaleDate.Equals(input.StaleDate)
                ) && 
                (
                    this.Priority == input.Priority ||
                    this.Priority.Equals(input.Priority)
                ) && 
                (
                    this.IosRelevanceScore == input.IosRelevanceScore ||
                    (this.IosRelevanceScore != null &&
                    this.IosRelevanceScore.Equals(input.IosRelevanceScore))
                ) && 
                (
                    this.IdempotencyKey == input.IdempotencyKey ||
                    (this.IdempotencyKey != null &&
                    this.IdempotencyKey.Equals(input.IdempotencyKey))
                ) && 
                (
                    this.IncludeAliases == input.IncludeAliases ||
                    this.IncludeAliases != null &&
                    input.IncludeAliases != null &&
                    this.IncludeAliases.SequenceEqual(input.IncludeAliases)
                ) && 
                (
                    this.IncludeSubscriptionIds == input.IncludeSubscriptionIds ||
                    this.IncludeSubscriptionIds != null &&
                    input.IncludeSubscriptionIds != null &&
                    this.IncludeSubscriptionIds.SequenceEqual(input.IncludeSubscriptionIds)
                ) && 
                (
                    this.IncludedSegments == input.IncludedSegments ||
                    this.IncludedSegments != null &&
                    input.IncludedSegments != null &&
                    this.IncludedSegments.SequenceEqual(input.IncludedSegments)
                ) && 
                (
                    this.ExcludedSegments == input.ExcludedSegments ||
                    this.ExcludedSegments != null &&
                    input.ExcludedSegments != null &&
                    this.ExcludedSegments.SequenceEqual(input.ExcludedSegments)
                ) && 
                (
                    this.Filters == input.Filters ||
                    this.Filters != null &&
                    input.Filters != null &&
                    this.Filters.SequenceEqual(input.Filters)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Event.GetHashCode();
                if (this.ActivityId != null)
                {
                    hashCode = (hashCode * 59) + this.ActivityId.GetHashCode();
                }
                if (this.EventAttributes != null)
                {
                    hashCode = (hashCode * 59) + this.EventAttributes.GetHashCode();
                }
                if (this.EventUpdates != null)
                {
                    hashCode = (hashCode * 59) + this.EventUpdates.GetHashCode();
                }
                if (this.Contents != null)
                {
                    hashCode = (hashCode * 59) + this.Contents.GetHashCode();
                }
                if (this.Headings != null)
                {
                    hashCode = (hashCode * 59) + this.Headings.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.StaleDate.GetHashCode();
                hashCode = (hashCode * 59) + this.Priority.GetHashCode();
                if (this.IosRelevanceScore != null)
                {
                    hashCode = (hashCode * 59) + this.IosRelevanceScore.GetHashCode();
                }
                if (this.IdempotencyKey != null)
                {
                    hashCode = (hashCode * 59) + this.IdempotencyKey.GetHashCode();
                }
                if (this.IncludeAliases != null)
                {
                    hashCode = (hashCode * 59) + this.IncludeAliases.GetHashCode();
                }
                if (this.IncludeSubscriptionIds != null)
                {
                    hashCode = (hashCode * 59) + this.IncludeSubscriptionIds.GetHashCode();
                }
                if (this.IncludedSegments != null)
                {
                    hashCode = (hashCode * 59) + this.IncludedSegments.GetHashCode();
                }
                if (this.ExcludedSegments != null)
                {
                    hashCode = (hashCode * 59) + this.ExcludedSegments.GetHashCode();
                }
                if (this.Filters != null)
                {
                    hashCode = (hashCode * 59) + this.Filters.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
