/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// UpdateUserRequest
    /// </summary>
    [DataContract(Name = "UpdateUserRequest")]
    public partial class UpdateUserRequest : IEquatable<UpdateUserRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateUserRequest" /> class.
        /// </summary>
        /// <param name="properties">properties.</param>
        /// <param name="refreshDeviceMetadata">refreshDeviceMetadata (default to false).</param>
        /// <param name="deltas">deltas.</param>
        public UpdateUserRequest(PropertiesObject properties = default(PropertiesObject), bool refreshDeviceMetadata = false, PropertiesDeltas deltas = default(PropertiesDeltas))
        {
            this.Properties = properties;
            this.RefreshDeviceMetadata = refreshDeviceMetadata;
            this.Deltas = deltas;
        }

        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        [DataMember(Name = "properties", EmitDefaultValue = false)]
        public PropertiesObject Properties { get; set; }

        /// <summary>
        /// Gets or Sets RefreshDeviceMetadata
        /// </summary>
        [DataMember(Name = "refresh_device_metadata", EmitDefaultValue = true)]
        public bool RefreshDeviceMetadata { get; set; }

        /// <summary>
        /// Gets or Sets Deltas
        /// </summary>
        [DataMember(Name = "deltas", EmitDefaultValue = false)]
        public PropertiesDeltas Deltas { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateUserRequest {\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("  RefreshDeviceMetadata: ").Append(RefreshDeviceMetadata).Append("\n");
            sb.Append("  Deltas: ").Append(Deltas).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateUserRequest);
        }

        /// <summary>
        /// Returns true if UpdateUserRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateUserRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateUserRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Properties == input.Properties ||
                    (this.Properties != null &&
                    this.Properties.Equals(input.Properties))
                ) && 
                (
                    this.RefreshDeviceMetadata == input.RefreshDeviceMetadata ||
                    this.RefreshDeviceMetadata.Equals(input.RefreshDeviceMetadata)
                ) && 
                (
                    this.Deltas == input.Deltas ||
                    (this.Deltas != null &&
                    this.Deltas.Equals(input.Deltas))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Properties != null)
                {
                    hashCode = (hashCode * 59) + this.Properties.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.RefreshDeviceMetadata.GetHashCode();
                if (this.Deltas != null)
                {
                    hashCode = (hashCode * 59) + this.Deltas.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
