/*
 * OneSignal
 *
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * Contact: devrel@onesignal.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = OneSignalApi.Client.OpenAPIDateConverter;

namespace OneSignalApi.Model
{
    /// <summary>
    /// Partial update applied with JSON Merge Patch (RFC 7396). Send only the fields you want to change. A null value clears a nullable field. Arrays such as nodes are replaced wholesale.
    /// </summary>
    [DataContract(Name = "UpdateJourneyRequest")]
    public partial class UpdateJourneyRequest : IEquatable<UpdateJourneyRequest>, IValidatableObject
    {
        /// <summary>
        /// Target state. Set active to activate a draft journey, or scheduled together with a future schedule.start_at to activate it later. Set archived to stop a running journey; archiving is permanent. Only scheduled and processing journeys can return to draft.
        /// </summary>
        /// <value>Target state. Set active to activate a draft journey, or scheduled together with a future schedule.start_at to activate it later. Set archived to stop a running journey; archiving is permanent. Only scheduled and processing journeys can return to draft.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StateEnum
        {
            /// <summary>
            /// Enum Draft for value: draft
            /// </summary>
            [EnumMember(Value = "draft")]
            Draft = 1,

            /// <summary>
            /// Enum Scheduled for value: scheduled
            /// </summary>
            [EnumMember(Value = "scheduled")]
            Scheduled = 2,

            /// <summary>
            /// Enum Active for value: active
            /// </summary>
            [EnumMember(Value = "active")]
            Active = 3,

            /// <summary>
            /// Enum Archived for value: archived
            /// </summary>
            [EnumMember(Value = "archived")]
            Archived = 4

        }


        /// <summary>
        /// Target state. Set active to activate a draft journey, or scheduled together with a future schedule.start_at to activate it later. Set archived to stop a running journey; archiving is permanent. Only scheduled and processing journeys can return to draft.
        /// </summary>
        /// <value>Target state. Set active to activate a draft journey, or scheduled together with a future schedule.start_at to activate it later. Set archived to stop a running journey; archiving is permanent. Only scheduled and processing journeys can return to draft.</value>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public StateEnum? State { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateJourneyRequest" /> class.
        /// </summary>
        /// <param name="name">Journey name..</param>
        /// <param name="description">Journey description. Send null to clear it..</param>
        /// <param name="audience">audience.</param>
        /// <param name="earlyExit">earlyExit.</param>
        /// <param name="reentryRules">reentryRules.</param>
        /// <param name="schedule">schedule.</param>
        /// <param name="nodes">Full ordered list of nodes, which replaces the existing graph wholesale. Preserve each node&#39;s server-assigned id from a prior fetch to keep in-flight users on that node; omit id to add a new node..</param>
        /// <param name="state">Target state. Set active to activate a draft journey, or scheduled together with a future schedule.start_at to activate it later. Set archived to stop a running journey; archiving is permanent. Only scheduled and processing journeys can return to draft..</param>
        /// <param name="concurrencyKey">Optional optimistic-concurrency token. Pass the concurrency_key from a prior fetch to reject the update with 409 if the journey changed. Omit to skip the check..</param>
        public UpdateJourneyRequest(string name = default(string), string description = default(string), JourneyAudience audience = default(JourneyAudience), JourneyEarlyExit earlyExit = default(JourneyEarlyExit), JourneyReentryRules reentryRules = default(JourneyReentryRules), JourneySchedule schedule = default(JourneySchedule), List<JourneyNode> nodes = default(List<JourneyNode>), StateEnum? state = default(StateEnum?), string concurrencyKey = default(string))
        {
            this.Name = name;
            this.Description = description;
            this.Audience = audience;
            this.EarlyExit = earlyExit;
            this.ReentryRules = reentryRules;
            this.Schedule = schedule;
            this.Nodes = nodes;
            this.State = state;
            this.ConcurrencyKey = concurrencyKey;
        }

        /// <summary>
        /// Journey name.
        /// </summary>
        /// <value>Journey name.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Journey description. Send null to clear it.
        /// </summary>
        /// <value>Journey description. Send null to clear it.</value>
        [DataMember(Name = "description", EmitDefaultValue = true)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Audience
        /// </summary>
        [DataMember(Name = "audience", EmitDefaultValue = false)]
        public JourneyAudience Audience { get; set; }

        /// <summary>
        /// Gets or Sets EarlyExit
        /// </summary>
        [DataMember(Name = "early_exit", EmitDefaultValue = true)]
        public JourneyEarlyExit EarlyExit { get; set; }

        /// <summary>
        /// Gets or Sets ReentryRules
        /// </summary>
        [DataMember(Name = "reentry_rules", EmitDefaultValue = true)]
        public JourneyReentryRules ReentryRules { get; set; }

        /// <summary>
        /// Gets or Sets Schedule
        /// </summary>
        [DataMember(Name = "schedule", EmitDefaultValue = true)]
        public JourneySchedule Schedule { get; set; }

        /// <summary>
        /// Full ordered list of nodes, which replaces the existing graph wholesale. Preserve each node&#39;s server-assigned id from a prior fetch to keep in-flight users on that node; omit id to add a new node.
        /// </summary>
        /// <value>Full ordered list of nodes, which replaces the existing graph wholesale. Preserve each node&#39;s server-assigned id from a prior fetch to keep in-flight users on that node; omit id to add a new node.</value>
        [DataMember(Name = "nodes", EmitDefaultValue = false)]
        public List<JourneyNode> Nodes { get; set; }

        /// <summary>
        /// Optional optimistic-concurrency token. Pass the concurrency_key from a prior fetch to reject the update with 409 if the journey changed. Omit to skip the check.
        /// </summary>
        /// <value>Optional optimistic-concurrency token. Pass the concurrency_key from a prior fetch to reject the update with 409 if the journey changed. Omit to skip the check.</value>
        [DataMember(Name = "concurrency_key", EmitDefaultValue = true)]
        public string ConcurrencyKey { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateJourneyRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Audience: ").Append(Audience).Append("\n");
            sb.Append("  EarlyExit: ").Append(EarlyExit).Append("\n");
            sb.Append("  ReentryRules: ").Append(ReentryRules).Append("\n");
            sb.Append("  Schedule: ").Append(Schedule).Append("\n");
            sb.Append("  Nodes: ").Append(Nodes).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  ConcurrencyKey: ").Append(ConcurrencyKey).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateJourneyRequest);
        }

        /// <summary>
        /// Returns true if UpdateJourneyRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateJourneyRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateJourneyRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.Audience == input.Audience ||
                    (this.Audience != null &&
                    this.Audience.Equals(input.Audience))
                ) && 
                (
                    this.EarlyExit == input.EarlyExit ||
                    (this.EarlyExit != null &&
                    this.EarlyExit.Equals(input.EarlyExit))
                ) && 
                (
                    this.ReentryRules == input.ReentryRules ||
                    (this.ReentryRules != null &&
                    this.ReentryRules.Equals(input.ReentryRules))
                ) && 
                (
                    this.Schedule == input.Schedule ||
                    (this.Schedule != null &&
                    this.Schedule.Equals(input.Schedule))
                ) && 
                (
                    this.Nodes == input.Nodes ||
                    this.Nodes != null &&
                    input.Nodes != null &&
                    this.Nodes.SequenceEqual(input.Nodes)
                ) && 
                (
                    this.State == input.State ||
                    this.State.Equals(input.State)
                ) && 
                (
                    this.ConcurrencyKey == input.ConcurrencyKey ||
                    (this.ConcurrencyKey != null &&
                    this.ConcurrencyKey.Equals(input.ConcurrencyKey))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                if (this.Audience != null)
                {
                    hashCode = (hashCode * 59) + this.Audience.GetHashCode();
                }
                if (this.EarlyExit != null)
                {
                    hashCode = (hashCode * 59) + this.EarlyExit.GetHashCode();
                }
                if (this.ReentryRules != null)
                {
                    hashCode = (hashCode * 59) + this.ReentryRules.GetHashCode();
                }
                if (this.Schedule != null)
                {
                    hashCode = (hashCode * 59) + this.Schedule.GetHashCode();
                }
                if (this.Nodes != null)
                {
                    hashCode = (hashCode * 59) + this.Nodes.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.State.GetHashCode();
                if (this.ConcurrencyKey != null)
                {
                    hashCode = (hashCode * 59) + this.ConcurrencyKey.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
